#########################################
# Surge Ruleset - Large Files Hosting IPs
# Last Updated: 2026-09-30T03:19:05.261Z
# Size: 10
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# This file contains ruleset for software updating & large file hosting.
#
# $content-hash-v1$:3DHRx9vcUsz5OlCR3SabDuknhj3oV6yiEcT_5PrnM1Y$
#########################################
DOMAIN-WILDCARD,download*.mediafire.com
DOMAIN-WILDCARD,ftp.??.debian.org
DOMAIN-WILDCARD,ftp.??.freebsd.org
DOMAIN-WILDCARD,s3.*.backblazeb2.com
DOMAIN-WILDCARD,*.s3.*.backblazeb2.com
DOMAIN-WILDCARD,cdn-*.comaps.app
DOMAIN-WILDCARD,cdn-*.comaps.tech
DOMAIN-WILDCARD,cdn-*.organicmaps.app
DOMAIN-WILDCARD,dl-*.mypikpak.com
URL-REGEX,^http://(.+)\.gvt\d\.com/edgedl
################## EOF ##################
