#########################################
# Surge Ruleset - GitLab
# Last Updated: 2026-09-30T03:19:05.261Z
# Size: 1
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# GitLab forbids usage from CN, HK, MO. This file contains ruleset for GitLab.
#
# $content-hash-v1$:fOOK4pfDWzn6jsysLKvMQ_pwVH4W-NTx4PyzTDJq1a4$
#########################################
DOMAIN-SUFFIX,gitlab.com
################## EOF ##################
