#########################################
# Surge Ruleset - Direct
# Last Updated: 2026-09-30T03:19:05.263Z
# Size: 2
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# $content-hash-v1$:hYYzXS4_V47tOoecxBN1k8edVZbJM8UXndOAfKEKSio$
#########################################
DOMAIN-SUFFIX,engage.cloudflareclient.com
PROCESS-NAME,nmap
################## EOF ##################
