#########################################
# Surge Ruleset - Internal Special
# Last Updated: 2026-09-30T03:19:05.263Z
# Size: 7
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# $content-hash-v1$:qAyXWQvIP97r0mZ0kRHNgbou0A2kU31gmvwSR5BqbTg$
#########################################
DOMAIN,github.com
DOMAIN,github.dev
DOMAIN,api.github.com
DOMAIN-SUFFIX,huggingface.co
DOMAIN,alive.github.com
DOMAIN-SUFFIX,githubcopilot.com
DOMAIN,android.googlesource.com
################## EOF ##################
