#########################################
# Surge Ruleset - Stream Services: Korean
# Last Updated: 2026-09-30T03:19:05.083Z
# Size: 3
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# - Naver TV
#
# $content-hash-v1$:sttfsUVnRbF-y8xKNur3N0TQ7YxVpz-zLYGDiTSRuZU$
#########################################
DOMAIN-SUFFIX,tv.naver.com
DOMAIN-SUFFIX,smartmediarep.com
USER-AGENT,Naver TV*
################## EOF ##################
