#########################################
# Surge Ruleset - Stream Services: Europe
# Last Updated: 2026-09-30T03:19:05.083Z
# Size: 10
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# - ITV
# - BBC
#
# $content-hash-v1$:aoQtHF6qyM5KYxWASN3s-Yb3OWQNFi5ZAuV_JKXrEWw$
#########################################
DOMAIN-SUFFIX,itv.com
DOMAIN-SUFFIX,bbc.co.uk
DOMAIN-SUFFIX,bbci.co.uk
DOMAIN,bbc.mp-pxcdn.com
DOMAIN-SUFFIX,tvlicensing.co.uk
DOMAIN,itvpnpmobile-a.akamaihd.net
DOMAIN-KEYWORD,bbcfmt
DOMAIN-KEYWORD,uk-live
USER-AGENT,ITV_Player*
USER-AGENT,BBCiPlayer*
################## EOF ##################
