#########################################
# Surge Ruleset - Microsoft Teams
# Last Updated: 2026-09-30T03:19:05.416Z
# Size: 10
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# Data from:
#  - https://endpoints.office.com/endpoints/worldwide (serviceArea=Skype, Microsoft Teams)
#
# This file contains domains used by Microsoft Teams.
#
# This file contains data from:
#   - https://endpoints.office.com/endpoints/worldwide
#
# $content-hash-v1$:aZYyJmrN6gRSTuljWSyMfjrVy1nmNfXfC7khrVG4JQc$
#########################################
DOMAIN,aka.ms
DOMAIN-SUFFIX,lync.com
DOMAIN-SUFFIX,skype.com
DOMAIN,adl.windows.com
DOMAIN-SUFFIX,teams.microsoft.com
DOMAIN-SUFFIX,teams.cloud.microsoft
DOMAIN,mlccdnprod.azureedge.net
DOMAIN,join.secure.skypeassets.com
DOMAIN-SUFFIX,streaming.mediaservices.windows.net
DOMAIN-SUFFIX,keydelivery.mediaservices.windows.net
################## EOF ##################
