#########################################
# Ruleset - Microsoft Teams
# Last Updated: 2026-09-29T16:14:05.472Z
# Size: 11
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# Data from:
#  - https://endpoints.office.com/endpoints/worldwide (serviceArea=Skype, Microsoft Teams)
#
# This file contains domains used by Microsoft Teams.
#
# This file contains data from:
#   - https://endpoints.office.com/endpoints/worldwide
#
# $content-hash-v1$:b4rd1c0NKKtX4MFsm5gyhbIkohu7l6RFeRVhFEglQkY$
#########################################
DOMAIN,7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe
DOMAIN,aka.ms
DOMAIN-SUFFIX,lync.com
DOMAIN-SUFFIX,skype.com
DOMAIN,adl.windows.com
DOMAIN-SUFFIX,teams.microsoft.com
DOMAIN-SUFFIX,teams.cloud.microsoft
DOMAIN,mlccdnprod.azureedge.net
DOMAIN,join.secure.skypeassets.com
DOMAIN-SUFFIX,streaming.mediaservices.windows.net
DOMAIN-SUFFIX,keydelivery.mediaservices.windows.net
################## EOF ##################
