#########################################
# Surge Ruleset - YouTube Music
# Last Updated: 2026-09-30T06:25:33.783Z
# Size: 3
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# This file contains rules for YouTube Music.
# It is written by hand, unlike the ruleset of YouTube: the community has no list for YouTube Music to generate it from.
# YouTube Music shares its domains with YouTube (see the youtube ruleset), so this file only has what sets it apart.
#
# $content-hash-v1$:ApStM85iKqGOoYhwecQaSAIUzv6XImiVHschJzD35mk$
#########################################
DOMAIN,music.youtube.com
USER-AGENT,com.google.ios.youtubemusic*
USER-AGENT,YouTubeMusic*
################## EOF ##################
