#########################################
# Surge Ruleset - Local DNS Mapping (BAIDU)
# Last Updated: 2026-09-30T03:19:05.304Z
# Size: 30
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# This is an internal rule that is only referenced by sukka_local_dns_mapping.sgmodule
# Do not use this file in your Rule section, all entries are included in non_ip/domestic.conf already.
#
# $content-hash-v1$:4dRrgped7QTp55w1qZbFSuaeGwe0XzaBeGGv4uPLTPE$
#########################################
DOMAIN-SUFFIX,91.com
DOMAIN-SUFFIX,dwz.cn
DOMAIN-SUFFIX,baidu.cn
DOMAIN-SUFFIX,baidu.com
DOMAIN-SUFFIX,bdimg.com
DOMAIN-SUFFIX,duapp.com
DOMAIN-SUFFIX,iqiyi.com
DOMAIN-SUFFIX,tieba.com
DOMAIN-SUFFIX,bcebos.com
DOMAIN-SUFFIX,bdydns.com
DOMAIN-SUFFIX,hao123.com
DOMAIN-SUFFIX,jomoxc.com
DOMAIN-SUFFIX,shifen.com
DOMAIN-SUFFIX,zybang.com
DOMAIN-SUFFIX,antpcdn.com
DOMAIN-SUFFIX,bcelive.com
DOMAIN-SUFFIX,jomodns.com
DOMAIN-SUFFIX,baidubce.com
DOMAIN-SUFFIX,baidubcr.com
DOMAIN-SUFFIX,baidupcs.com
DOMAIN-SUFFIX,bdstatic.com
DOMAIN-SUFFIX,iqiyipic.com
DOMAIN-SUFFIX,xiaodutv.com
DOMAIN-SUFFIX,zuoyebang.com
DOMAIN-SUFFIX,baidustatic.com
DOMAIN-SUFFIX,baiducontent.com
DOMAIN-SUFFIX,yunjiasu-cdn.net
DOMAIN,upos-sz-mirrorbd.bilivideo.com
DOMAIN,upos-sz-mirrorbdb.bilivideo.com
DOMAIN,upos-sz-mirrorbos.bilivideo.com
################## EOF ##################
