#########################################
# Surge Ruleset - Local DNS Mapping (BILIBILI)
# Last Updated: 2026-09-30T03:19:05.304Z
# Size: 16
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# This is an internal rule that is only referenced by sukka_local_dns_mapping.sgmodule
# Do not use this file in your Rule section, all entries are included in non_ip/domestic.conf already.
#
# $content-hash-v1$:6Dl4ewKEstrVyivh7cUOBC6Jf4gXa5wdzQcwD04orC0$
#########################################
DOMAIN,acg.tv
DOMAIN,b23.tv
DOMAIN-SUFFIX,biliapi.com
DOMAIN-SUFFIX,biliapi.net
DOMAIN-SUFFIX,bilibili.cn
DOMAIN-SUFFIX,acgvideo.com
DOMAIN-SUFFIX,bilibili.com
DOMAIN-SUFFIX,bilicdn1.com
DOMAIN-SUFFIX,biligame.com
DOMAIN-SUFFIX,biligame.net
DOMAIN-SUFFIX,bilivideo.cn
DOMAIN-SUFFIX,bulicdn2.com
DOMAIN-SUFFIX,bilicomic.com
DOMAIN-SUFFIX,bilivideo.com
DOMAIN-SUFFIX,bilivideo.net
DOMAIN-SUFFIX,bilicomics.com
################## EOF ##################
