#########################################
# Surge Ruleset - Local DNS Mapping (HOTSPOT_CAPTIVE_PORTAL)
# Last Updated: 2026-09-30T03:19:05.304Z
# Size: 3
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# This is an internal rule that is only referenced by sukka_local_dns_mapping.sgmodule
# Do not use this file in your Rule section, all entries are included in non_ip/domestic.conf already.
#
# $content-hash-v1$:xgGFtzSZbcqjSEdYZIULz0xqVxjih1fCj4TYHEbervQ$
#########################################
DOMAIN,captive.apple.com
DOMAIN-SUFFIX,securelogin.com.cn
DOMAIN,hotspot.cslwifi.com
################## EOF ##################
