# $ custom_build_script

# What no list of domains can carry. The rest of the ruleset is generated, see Build/build-service-rulesets.ts

# >> Gemini
# Here is how gemini.google.com doing HTTP 429 right now:
#
# without a special cookie, gemini.google.com will return HTTP 302 to the following URL with
# a special state token URL parameter:
# https://www.google.com/sorry/index?continue=https://gemini.google.com/...
#
# On https://www.google.com/sorry/index?continue=xxx, the CDN edge will validate this state token,
# compare the client IPs, and reject the request with HTTP 429 if the IPs are mismatched
#
# If the IP matches, the CDN edge will return a HTTP 302 redirect back to https://gemini.google.com
# with another special state token URL parameter telling gemini.google.com stop returning HTTP 302
# back to www.google.com/sorry/index?continue=xxx and start serving the real content.
#
# We can simply matches www.google.com/sorry/index?continue=xxx and proxy this as well
#
# Note that you will need to enable MitM www.google.com for this rule to work.
URL-REGEX,https://www\.google\.com/.*continue=https://gemini\.google\.com.+
