# $ custom_build_script

# What no list of domains can carry. The rest of the ruleset is generated, see Build/build-service-rulesets.ts

# >> Apple Maps
PROCESS-NAME,com.apple.geod
PROCESS-NAME,mapspushd
PROCESS-NAME,com.apple.Maps

# >> Apple System Services
PROCESS-NAME,apsd
PROCESS-NAME,fmfd
PROCESS-NAME,findmydevice-user-agent
PROCESS-NAME,CoreLocationAgent
PROCESS-NAME,WeatherWidget
