# $ meta_title Surge Ruleset - Reject (REJECT-DROP)

# >> Tencent Lemon

PROCESS-NAME,Tencent Lemon
PROCESS-NAME,LemonMonitor
PROCESS-NAME,LemonDaemon
PROCESS-NAME,LemonAgent
PROCESS-NAME,LemonService

# >> Windows Update Delivery Optimization (WUDO) use 7680 port
DEST-PORT,7680

# >> Misc
DOMAIN-KEYWORD,bahoom
DOMAIN,daisydiskapp.com
DOMAIN-SUFFIX,adobe.io
DOMAIN-SUFFIX,adobestats.io
DOMAIN-SUFFIX,genuine.autodesk.com
AND,((DOMAIN-KEYWORD,genuine), (DOMAIN-KEYWORD,autodesk))
DOMAIN-SUFFIX,0.0.198.in-addr.arpa

# >> Fake News Website
# https://www.cool3c.com/article/239818 (true story: https://xiaomitime.com/is-xiaomi-planning-a-google-free-android-future-with-hyperos-42899/ )
DOMAIN-SUFFIX,cool3c.com

# >> Misc

# Meituan Live
DOMAIN-SUFFIX,mtvod.meituan.net
DOMAIN-SUFFIX,mtvod-ali.meituan.net
DOMAIN-KEYWORD,-flv.meituan.net
DOMAIN-KEYWORD,-live.meituan.net

# Meituan loans and credit cards
DOMAIN-SUFFIX,expenses-fe.meituan.com
DOMAIN-KEYWORD,-fin.meituan.com
DOMAIN-SUFFIX,logan.sankuai.com

# Meituan Video
DOMAIN-SUFFIX,contents.meituan.com

# Meituan Games
DOMAIN-SUFFIX,game.meituan.com

# Ele.me clean up
DOMAIN-SUFFIX,microfin.ele.me
DOMAIN-SUFFIX,httpizza.ele.me

# Fliggy auto-update
DOMAIN,app-download.fliggy.com

# Google Timeline / Location
DOMAIN,userlocation.googleapis.com
DOMAIN,userlocation.googleapis.com
# https://locationhistory-pa.googleapis.com/google.internal.locationhistory.v1.LocationHistoryService/GetSettings
# https://locationhistory-pa.googleapis.com/google.internal.locationhistory.v1.LocationHistoryService/ListTombstones
# https://locationhistory-pa.googleapis.com/google.internal.locationhistory.v1.LocationHistoryService/UpdateDeviceMetadata
DOMAIN,locationhistory-pa.googleapis.com
DOMAIN,locationhistoryaggregates-pa.googleapis.com
DOMAIN,locationhistoryplacedetails-pa.googleapis.com

# NetEase Cloud Music LOOK Live
DOMAIN-SUFFIX,look.163.com

# >> MIUI/HyperOS clean up
DOMAIN,mpush-api.aliyun.com
# Xiaomi Mibi (Mi Coin)
DOMAIN-SUFFIX,mibi.xiaomi.com
# Xiaomi carrier services
DOMAIN-SUFFIX,xiaomimobile.com
# Xiaomi Finance
DOMAIN-SUFFIX,jr.mi.com
DOMAIN-SUFFIX,jr.airstarfinance.net
# Xiaomi Video
DOMAIN-SUFFIX,pipi.cn
# Xiaomi credit card
DOMAIN-SUFFIX,lmk.mipay.com
# JPush (Jiguang Push), not HTTP, uses the domain registry's default NS
DOMAIN-SUFFIX,easytomessage.com
# Xiaomi App Store
DOMAIN,fyb-2.cdn.bcebos.com
# Xiaomi Quick App framework
DOMAIN-SUFFIX,hybrid.xiaomi.com
# Xiaomi Midc
DOMAIN-SUFFIX,api.miwifi.com


# >> China Post Youle: loans, wealth management, farmer-support mall
DOMAIN-SUFFIX,ule.com
DOMAIN-SUFFIX,ulecdn.com

# >> ele.me loan
DOMAIN,loan-supermarket.faas.ele.me

# >> Tongdun risk control
DOMAIN-SUFFIX,tongdun.net

# >> 12306
# I don't care about iOS App. Android App just works fine w/ this blocked
DOMAIN,ad.12306.cn
DOMAIN,push.12306.cn

# >> Xianyu (Goofish) and Taobao Live
DOMAIN-SUFFIX,video.goofish.com
DOMAIN-SUFFIX,video-zb.cloudvideocdn.taobao.com

# >> China Unicom App
DOMAIN-SUFFIX,newbuy.chinaunicom.cn
DOMAIN-SUFFIX,mall.10010.cn
DOMAIN-SUFFIX,unicompayment.com
DOMAIN,epay.10010.com
