#########################################
# Surge Ruleset - CDN
# Last Updated: 2026-09-30T03:19:05.257Z
# Size: 3
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# This file contains CDN IP addresses for object storage and static assets CDN.
#
# $content-hash-v1$:5I5kuyeSaE6vsN7bbQo_5eYpCqNQcyERh4V4t9bvt4U$
#########################################
IP-CIDR,162.159.200.1/32
IP-CIDR,162.159.200.123/32
IP-CIDR,185.199.108.0/22
################## EOF ##################
