#########################################
# Surge Ruleset - Mainland China Supplement CIDR
# Last Updated: 2026-09-30T03:19:05.258Z
# Size: 2
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# This file contains IPs broadcast inside Mainland China.
#
# $content-hash-v1$:EFMhBC8lXVgbXu8MNunOtOsj0-AZt1GU6BBh0Vi1GMU$
#########################################
IP-CIDR,140.205.1.0/24,no-resolve
IP-CIDR,162.14.0.0/18,no-resolve
################## EOF ##################
