#########################################
# Surge Ruleset - LAN
# Last Updated: 2026-09-30T03:19:05.258Z
# Size: 11
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# Includes rules for LAN IP addresses and .local suffix.
#
# $content-hash-v1$:ooItcBYZrE5_7xab_8IiuYIM3nmYS4aj0pmM7Qn5V5I$
#########################################
IP-CIDR,0.0.0.0/8
IP-CIDR,10.0.0.0/8
IP-CIDR,100.64.0.0/10
IP-CIDR,127.0.0.0/8
IP-CIDR,169.254.0.0/16
IP-CIDR,172.16.0.0/12
IP-CIDR,192.168.0.0/16
IP-CIDR,224.0.0.0/4
IP-CIDR6,::1/128
IP-CIDR6,fc00::/7
IP-CIDR6,fe80::/10
################## EOF ##################
