#########################################
# Surge Ruleset - Stream Services IPs: Korean
# Last Updated: 2026-09-30T03:19:05.083Z
# Size: 0
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# - Naver TV
#
# $content-hash-v1$:aT4kv-Vj2VyZILYV9Gh40OLSIFiy1CfmOID_I3ukG_g$
#########################################
################## EOF ##################
