#########################################
# Surge Ruleset - Stream Services IPs: Japan
# Last Updated: 2026-09-30T08:58:17.129Z
# Size: 0
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# - DMM
# - AbemaTV
# - niconico
# - Hulu Japan
# - TVer
# - NHK
#
# None of the services has addresses that its owner announces.
#
# $content-hash-v1$:ZxT3-1QGO_iL49DWNiMD3obGsd1BAflOQ8tTu5eeTSA$
#########################################
################## EOF ##################
