#########################################
# Surge Ruleset - Stream Services IPs: Europe
# Last Updated: 2026-09-30T08:58:17.129Z
# Size: 0
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# - ITV
# - BBC
#
# None of the services has addresses that its owner announces.
#
# $content-hash-v1$:iWG1Je9r3V6Qt1X0yP5o6En8VB9K71jUp777noNGbGo$
#########################################
################## EOF ##################
