#########################################
# Surge Ruleset - Stream Services IPs: North America
# Last Updated: 2026-09-30T13:03:48.786Z
# Size: 0
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# - Fox Now
# - Fox+
# - Hulu
# - Vudu
# - Pluto TV
# - SHOWTIME
# - encoreTVB
# - Discovery+
# - Paramount+
# - Peacock
# - Crackle
# - Tubi TV
#
# None of the services has addresses that its owner announces.
#
# $content-hash-v1$:6ZHn2ln2f4EVG1nuiH1ptSnHNzMeUlGx3SatOOQW2Ew$
#########################################
################## EOF ##################
