#########################################
# Surge Ruleset - Stream Services IPs: Europe
# Last Updated: 2026-09-30T03:19:05.083Z
# Size: 0
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# - ITV
# - BBC
#
# $content-hash-v1$:vwNH5mO7uNc9VmHPi78uHd-9OSbYMR8U2EA4_bSxoUk$
#########################################
################## EOF ##################
