#########################################
# Surge Ruleset - Stream Services IPs: Korean
# Last Updated: 2026-09-30T08:58:16.536Z
# Size: 0
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# - Naver TV
#
# None of the services has addresses that its owner announces.
#
# $content-hash-v1$:eZGLQLAxBaHrXRLb4rl4ldXiibOmkbj10OUmLPDqQvQ$
#########################################
################## EOF ##################
