#########################################
# Ruleset - Microsoft Teams IP CIDR
# Last Updated: 2026-09-29T16:14:05.472Z
# Size: 10
# License: AGPL 3.0
# Homepage: https://ruleset.skk.moe
# GitHub: https://github.com/SukkaW/Surge
#
# Data from:
#  - https://endpoints.office.com/endpoints/worldwide (serviceArea=Skype, Microsoft Teams)
#
# This file contains IP ranges used by Microsoft Teams (media, calling and meetings).
#
# This file contains data from:
#   - https://endpoints.office.com/endpoints/worldwide
#
# $content-hash-v1$:_FTTr_rjCTJZLwNp0m-47BGxclV2HKI2WyetFp9Nd4c$
#########################################
DOMAIN,7h15.ru1353t.1s.m4d3.by.5ukk4w.skk.moe
IP-CIDR,52.112.0.0/14,no-resolve
IP-CIDR,52.122.0.0/15,no-resolve
IP-CIDR6,2603:1063::/38,no-resolve
IP-CIDR6,2603:1027::/48,no-resolve
IP-CIDR6,2603:1037::/48,no-resolve
IP-CIDR6,2603:1047::/48,no-resolve
IP-CIDR6,2603:1057::/48,no-resolve
IP-CIDR6,2620:1ec:6::/48,no-resolve
IP-CIDR6,2620:1ec:40::/42,no-resolve
################## EOF ##################
