#########################################
# Surge Ruleset - Telegram ASN
# Last Updated: 2026-09-30T03:19:06.021Z
# Size: 5
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# This file contains ASN owned/used by Telegram Messenger.
# The ASNs are found by looking up which ASNs announce the prefixes Telegram publishes (see ip/telegram) in Team Cymru's IP to ASN mapping (https://team-cymru.com/community-services/ip-asn-mapping/), and are kept as long as the AS is registered under the name of Telegram.
# Note that unlike "ip/telegram" file which is based on officially released list by Telegram themselves. Use this file at your own risk.
#
# $content-hash-v1$:ukIAqEXPq17tDjzNr4ULca2Gp_o5LbQc0GiYADYdUCo$
#########################################
IP-ASN,44907
IP-ASN,59930
IP-ASN,62014
IP-ASN,62041
IP-ASN,211157
################## EOF ##################
