#########################################
# Surge Ruleset - iCloud Private Relay
# Last Updated: 2026-09-30T03:19:05.257Z
# Size: 6
# License: AGPL 3.0
# GitHub: https://github.com/kuraudowelle/Surge-Ruleset
#
# This file contains domains for iCloud Private Relay Endpoint.
#
# $content-hash-v1$:QMY1VhZnqPb8w6hN-tUrgjq9An7JAeCseQIFHbjJ25k$
#########################################
mask.icloud.com
mask-h2.icloud.com
mask.apple-dns.net
mask-api.icloud.com
mask-canary.icloud.com
canary.mask.apple-dns.net
################## EOF ##################
